# Generated by Django 3.2.5 on 2021-07-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210716_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section1',
            name='titel',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
