# Generated by Django 3.2.5 on 2021-07-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_section3part1_section3part2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footerrighttitel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Footertitel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
            ],
        ),
    ]
