# Generated by Django 3.2.5 on 2021-07-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_footerrighttitel_footertitel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footerrighttitel',
        ),
    ]
