# Generated by Django 3.2.5 on 2021-07-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_footertitelright'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footerparamsright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=255)),
            ],
        ),
    ]
