# Generated by Django 3.2.5 on 2021-07-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_footerparamsright'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footertitelleft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=500)),
            ],
        ),
    ]
