# Generated by Django 3.2.5 on 2021-07-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_footertitelleft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footeraddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=555)),
            ],
        ),
    ]
