# Generated by Django 3.2.5 on 2021-07-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_footermobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footeremail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500)),
            ],
        ),
    ]
