# Generated by Django 3.2.5 on 2021-07-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_footeremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footerfax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fax', models.CharField(max_length=555)),
            ],
        ),
        migrations.CreateModel(
            name='Footerphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
    ]
