# Generated by Django 3.2.5 on 2021-07-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_footerimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='param1',
            new_name='param',
        ),
        migrations.RemoveField(
            model_name='header',
            name='param2',
        ),
        migrations.RemoveField(
            model_name='header',
            name='param3',
        ),
    ]
