# Generated by Django 3.2.5 on 2021-07-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='param',
            field=models.TextField(max_length=5555),
        ),
    ]
