# Generated by Django 3.2.5 on 2021-07-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_rename_param_contactusaddress_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactusimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aboutus/%Y/%m/%d/')),
            ],
        ),
    ]
