# Generated by Django 3.2.5 on 2021-07-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_contactusimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactusForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=555)),
                ('phone', models.CharField(max_length=255)),
                ('subject', models.TextField(max_length=1000)),
            ],
        ),
    ]
